// examples/phonon-and-angular/src/app/home/home.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {
  @Input() title:string;
  @Input() app:object;

  constructor() { }

  ngOnInit() {
    this.app.on({page: 'home', preventClose: true}, this)
  }

}

<div data-page="true" data-alias="home">
  <header class="header-bar">
    <div class="center">
      <h1 class="title">{{ title }}</h1>
    </div>
  </header>
  <div class="content">

    <ul class="list">
      <li class="divider">Select a pizza</li>
      <li><a class="padded-list" href="#!page-two/margherita">Margherita</a></li>
      <li><a class="padded-list" href="#!page-two/calzone">Cheese Calzone</a></li>
      <li><a class="padded-list" href="#!page-two/pesto">Pesto Pizza</a></li>
      <li><a class="padded-list" href="#!page-two/roma">Roma</a></li>
      <li><a class="padded-list" href="#!page-two/prosciutto">Prosciutto</a></li>
      <li><a class="padded-list" href="#!page-two/funghi">Funghi</a></li>
    </ul>

  </div>
</div>

// examples/phonon-and-vue/src/components/Home.vue
<template>
  <div class="app-page" data-page="true" :data-alias="$options.name">
    <header class="header-bar">
      <div class="center">
        <h1 class="title">Phonon + Vue</h1>
      </div>
    </header>
    <div class="content">

      <ul class="list">
        <li class="divider">Select a pizza</li>
        <li><a class="padded-list" href="#!page-two/margherita">Margherita</a></li>
        <li><a class="padded-list" href="#!page-two/calzone">Cheese Calzone</a></li>
        <li><a class="padded-list" href="#!page-two/pesto">Pesto Pizza</a></li>
        <li><a class="padded-list" href="#!page-two/roma">Roma</a></li>
        <li><a class="padded-list" href="#!page-two/prosciutto">Prosciutto</a></li>
        <li><a class="padded-list" href="#!page-two/funghi">Funghi</a></li>
      </ul>

    </div>
  </div>
</template>

<script>
export default {
  name: 'home',
  props: {
    app: {
      type: Object,
      require: true,
    },
  },
  mounted() {
    this.app.on({ page: 'home', preventClose: false, content: null });
  },
};
</script>
