// examples/pizza-app-with-vue/src/App.vue
<template>
  <div id="app">
    <home :app="app" />
    <page-two :app="app" />
  </div>
</template>

<script>
import 'phonon/dist/css/phonon.css'

import phonon from 'phonon/dist/js/phonon-core'
import Home from './components/Home.vue'
import PageTwo from './components/PageTwo.vue'

export default {
  name: 'app',
  data () {
    return {
      app: phonon.navigator()
    }
  },
  mounted () {
    phonon.options({
      navigator: {
        defaultPage: 'home',
        animatePages: true,
        enableBrowserBackButton: true
      },
      i18n: null // for this example, we do not use internationalization
    })

    this.app.start()
  },
  components: {
    Home,
    PageTwo
  }
}
</script>

// examples/pizza-app-with-angular/src/app/app.component.ts
import { Component, OnInit, ViewEncapsulation } from '@angular/core';
import phonon from 'phonon/dist/js/phonon-core'

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: [
    './app.component.css',
    '../../node_modules/phonon/dist/css/phonon.css'    
  ],
  encapsulation: ViewEncapsulation.None, 
})
export class AppComponent implements OnInit {
  title:string = 'Phonon + Angular';
  app:object = null

  ngOnInit() {
    this.app = phonon.navigator()

    phonon.options({
      navigator: {
        defaultPage: 'home',
        animatePages: true,
        enableBrowserBackButton: true
      },
      i18n: null // for this example, we do not use internationalization
    })

    this.app.start();
  }
}
