// examples/pizza-app-with-vue/components/App.vue
<template>
	<home :app="app"></home>
	<page-two :app="app"></page-two>
</template>

<script>

	import Home from './Home.vue'
	import PageTwo from './PageTwo.vue'

	export default {

		data() {
			return {
				app: phonon.navigator()
			}
		},

 		ready: function () {

			phonon.options({
				navigator: {
					defaultPage: 'home',
					animatePages: true,
					enableBrowserBackButton: true
				},
				i18n: null // for this example, we do not use internationalization
			})

			this.app.start()
		},

		components: { Home, PageTwo }
	}
</script>

// examples/pizza-app-with-angular/src/app/app.component.ts
import { Component, OnInit, ViewEncapsulation } from '@angular/core';
import phonon from 'phonon/dist/js/phonon-core'

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: [
    './app.component.css',
    '../../node_modules/phonon/dist/css/phonon.css'    
  ],
  encapsulation: ViewEncapsulation.None, 
})
export class AppComponent implements OnInit {
  title:string = 'Phonon + Angular';
  app:object = null

  ngOnInit() {
    this.app = phonon.navigator()

    phonon.options({
      navigator: {
        defaultPage: 'home',
        animatePages: true,
        enableBrowserBackButton: true
      },
      i18n: null // for this example, we do not use internationalization
    })

    this.app.start();
  }
}
